version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name work5 --s3-location s3://mywork5/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src